[tool.poetry]
name = "vcs-client"
version = "0.1.0"
description = ""
authors = ["Jasmit Tarang <jasmit.tarang@bp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
